channels:
  - conda-forge
dependencies:
  - python=3.12
  - c-blosc2
  - dask=2025.5.1
  - distributed=2025.5.1
  - dask-image=2024.5.3
  - flatten_json
  - h5py=3.11.0
  - imagecodecs
  - lz4>=4.3.2
  - numcodecs
  - numpy>=1.26.0,<2
  - pip
  - psutil>=5.7.2
  - pydantic=2.7.1
  - python-blosc2=3.0.0
  - pyyaml
  - roifile
  - scikit-image>=0.21.0
  - scikit-learn>=1.4.1
  - tornado=6.4
  - zarr=2.18.7
  - pip:
    - cellpose==4.0.6
    - pynrrd
    - ome-zarr-models==0.1.6
    - torch==2.6.0
    - torchvision
